version: '3.3'

services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    env_file: /home/hamza/test-deploy/.env
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=test_db
    ports:
      - 3307:3306
    volumes:
      - db:/var/lib/mysql
    networks:
      - backend
  
  test-api:
    depends_on:
      - mysqldb
    build: /home/hamza/test-deploy/API
    restart: unless-stopped
    env_file: /home/hamza/test-deploy/.env
    ports:
      - 6868:6868
    environment:
      - DB_HOST=mysqldb
      - DB_USER=root
      - DB_PASSWORD=123456
      - DB_NAME=test_db
      - DB_PORT=3306
      - CLIENT_ORIGIN=http://127.0.0.1
    networks:
      - backend
      - frontend

  test-ui:
    depends_on:
      - test-api
    build:
      context: /home/hamza/test-deploy/frontend
      args:
        - REACT_APP_API_BASE_URL=$CLIENT_API_BASE_URL
    ports:
      - 80:80
    networks:
      - frontend  
  
    
  
volumes: 
  db:

networks:
  backend:
  frontend:
